[project]
name = "main-bank-account-agent"
version = "0.1.0"
description = "BankAccountAgent"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai-agents>=0.2.10",
    "python-dotenv>=1.1.1",
]
